###############################################################################
##                                                                           ##
##                                                                           ##
##                            (c) Airbus DS Geo                              ##
##                                                                           ##
##                                                                           ##
##                    Contact: frederic.bages@airbus.com                     ##
##                                                                           ##
###############################################################################

info:
  title: Airbus Defense and Space Geo - API root specification
  description: |
    This document describes Airbus Defense and Space Geo APIs. 
  contact:
    url: http://www.geoapi-airbusds.com

  version: '1.0'

###############################################################################
##                                                                           ##
##                           GENERAL CONFIGuRATION                           ##
##                                                                           ##
###############################################################################

consumes:
  - application/json

produces:
  - application/x-yaml

schemes:
  - https

host: airbusgeo.github.io

swagger: '2.0'

###############################################################################
##                                                                           ##
##                           OBJECTS DOCUMENTATION                           ##
##                                                                           ##
###############################################################################



        
###############################################################################
##                                                                           ##
##                         END POINTS DOCUMENTATION                          ##
##                                                                           ##
###############################################################################

paths:


  /api-docs/view.yaml: 
    get:
      summary: Returns the yaml specification of the View API.
      description: View API documentation. A beautified version can be consulted within the [browser](https://airbusgeo.github.io/geoapi-viewer/?url=https://airbusgeo.github.io/api-docs/view.yaml)
      responses:
        '200':
          description: Request successful
      tags: 
        - Specification 
